---
- name: use french debian mirror
  lineinfile: dest=/etc/apt/sources.list regexp='^(.*)uk\.(.*)' line='\1fr.\2'

- name: upgrade the distro
  apt: update_cache=yes upgrade=yes cache_valid_time=3600

- name: install common packages
  apt: pkg={{ item }} state=latest
  with_items:
    - vim
    - curl
    - gnupg
    - rsync
    - wget
    - ack-grep
    - python-pycurl